In [1]:
import numpy as np
import gym
import random
import time
from IPython.display import clear_output

env = gym.make("FrozenLake-v1")

In [4]:
action_space_size = env.action_space.n
state_space_size = env.observation_space.n

q_table = np.zeros((state_space_size, action_space_size))
q_table.shape

(16, 4)

In [12]:
num_episodes = 10000
max_steps_per_episode = 100

learning_rate = 0.05
discount_rate = 0.95

exploration_rate = 1
max_exploration_rate = 1
min_exploration_rate = 0.01
exploration_decay_rate = 0.005

In [13]:
rewards_all_episodes = []

# Q-learning algorithm
for episode in range(num_episodes):
    # initialize new episode params
    state = env.reset()
    done = False
    rewards_current_episode = 0

    for step in range(max_steps_per_episode): 
        # Exploration-exploitation trade-off
        exploration_rate_threshold = random.uniform(0, 1)
        
        action = np.argmax(q_table[state,:]) \
            if exploration_rate_threshold > exploration_rate \
            else env.action_space.sample()
            
        # Take new action
        new_state, reward, done, info = env.step(action)
        
        # Update Q-table
        q_table[state, action] = q_table[state, action] * (1 - learning_rate) + \
            learning_rate * (reward + discount_rate * np.max(q_table[new_state, :]))
        
        # Set new state
        state = new_state
        # Add new reward 
        rewards_current_episode += reward
        
        if done: break

    # Exploration rate decay
    exploration_rate = min_exploration_rate + \
    (max_exploration_rate - min_exploration_rate) * np.exp(-exploration_decay_rate*episode)
    
    # Add current episode reward to total rewards list
    rewards_all_episodes.append(rewards_current_episode)

In [14]:
# Calculate and print the average reward per thousand episodes
rewards_per_thousand_episodes = np.split(np.array(rewards_all_episodes),num_episodes/1000)
count = 1000

print("********Average reward per thousand episodes********\n")
for r in rewards_per_thousand_episodes:
    print(count, ": ", str(sum(r/1000)))
    count += 1000

********Average reward per thousand episodes********

1000 :  0.35000000000000026
2000 :  0.6540000000000005
3000 :  0.6610000000000005
4000 :  0.6610000000000005
5000 :  0.5880000000000004
6000 :  0.7030000000000005
7000 :  0.6680000000000005
8000 :  0.6660000000000005
9000 :  0.7050000000000005
10000 :  0.6240000000000004


In [15]:
print("\n\n********Q-table********\n")
print(q_table)



********Q-table********

[[0.18559123 0.14204523 0.13354215 0.12822316]
 [0.09392915 0.09048395 0.08984873 0.14735747]
 [0.13394688 0.11775437 0.11647058 0.11480978]
 [0.09615205 0.09773835 0.09475449 0.11239951]
 [0.20271396 0.13651611 0.12944257 0.10313009]
 [0.         0.         0.         0.        ]
 [0.09561748 0.06480232 0.12797508 0.06433139]
 [0.         0.         0.         0.        ]
 [0.14936024 0.17270677 0.13901865 0.28023874]
 [0.2289602  0.3800658  0.30304911 0.2319661 ]
 [0.37080776 0.29170852 0.30220214 0.18018998]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.3298097  0.37372204 0.500728   0.39844297]
 [0.4992862  0.68754463 0.5823792  0.58459301]
 [0.         0.         0.         0.        ]]


In [18]:
# Watch our agent play Frozen Lake by playing the best action 
# from each state according to the Q-table

for episode in range(3):
    # initialize new episode params
    state = env.reset()
    done = False
    print("*****EPISODE ", episode+1, "*****\n\n\n\n")
    time.sleep(1)

    for step in range(max_steps_per_episode):        
        # Show current state of environment on screen
        clear_output(wait=True)
        env.render()
        time.sleep(0.3)
        
        # Choose action with highest Q-value for current state       
        # Take new action
        action = np.argmax(q_table[state,:])        
        new_state, reward, done, info = env.step(action)

        if done:
            clear_output(wait=True)
            env.render()
            
            if reward == 1:
                print("****You reached the goal!****")
                time.sleep(3)

            else:
                print("****You fell through a hole!****")
                time.sleep(3)
                clear_output(wait=True)
            break        

        # Set new state
        state = new_state

env.close()

  (Down)
SFFF
FHFH
FFFH
HFFG
****You reached the goal!****
